version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = ""
s3_bucket = ""
s3_prefix = ""
region = ""
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = ""
image_repositories = [
	"ShortenFunction=",
	"RedirectFunction="
]
